
services:
  nginx:
    image: nginx:1.27.0-perl
    
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./project/flask-app/static:/usr/share/nginx/html/static;
      - ./project/flask-app/templates:/usr/share/nginx/html/html;
    depends_on:
      - web
    networks:
      - front_net

  web:
    build:
      context: .
  
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
    - es
    networks:
      - front_net
      - back_net

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    restart: always
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - back_net


volumes:
  esdata:

networks:
  front_net:
  back_net:
