version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - webnet

  web:
    build:
      context: .
      dockerfile: Dockerfile.light
    ports:
      - "5001:5000"  # Change the host port to 5001
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    volumes:
      - flask_data:/app/data
    depends_on:
      - elasticsearch
    networks:
      - webnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - webnet

volumes:
  esdata:
  static_volume:
  flask_data:

networks:
  webnet:
